using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace SmashggNet.Models
{
    public class Tournament
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        /// <summary>
        /// The id of the series
        /// </summary>
        [JsonProperty("seriesId")]
        public int? SeriesId { get; set; }

        /// <summary>
        /// The user's id who owns this tournament object.
        /// </summary>
        [JsonProperty("ownerId")]
        public int? OwnerId { get; set; }

        /// <summary>
        /// The name of the tournament in question
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// A short version of the name used as URL
        /// </summary>
        [JsonProperty("slug")]
        public string Slug { get; set; }

        /// <summary>
        /// URL to the tournament on smash.gg.
        /// WARNING This is generated by SmashggNet and might be inaccurate.
        /// </summary>
        public string Url => $"https://www.smash.gg/tournament/{Slug}";

        [JsonProperty("timezone")]
        public string Timezone { get; set; }

        [JsonProperty("private")]
        public bool? Private { get; set; }

        /// <summary>
        /// The date the tournament start at in the TODO add format
        /// Use <see cref="EndDate"/> to get the DateTime object this corresponds to.
        /// </summary>
        [JsonProperty("startAt")]
        public long StartAt { get; set; }

        /// <summary>
        /// The date the tournament ends at in the TODO add format
        /// Use <see cref="EndDate"/> to get the DateTime object this corresponds to.
        /// </summary>
        [JsonProperty("endAt")]
        public long EndAt { get; set; }

        /// <summary>
        /// The date the tournament starts at derived from <see cref="StartAt"/>
        /// </summary>
        public DateTime StartDate => new DateTime(1970, 1, 1, 0, 0, 0).AddSeconds(StartAt);

        /// <summary>
        /// The date the tournament ends at derived from <see cref="EndAt"/>
        /// </summary>
        public DateTime EndDate => new DateTime(1970, 1, 1, 0, 0, 0).AddSeconds(EndAt);

        [JsonProperty("venueName")]
        public string VenueName { get; set; }

        [JsonProperty("venueAddress")]
        public string VenueAddress { get; set; }

        /// <summary>
        /// A collection of images that are for the tournament.
        /// </summary>
        [JsonProperty("images")]
        public List<SmashggImage> Images { get; set; }
    }
}